name: mezamasi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  camera: ^0.11.0
  permission_handler: ^12.0.1
  intl: ^0.19.0
  flutter_ringtone_player: ^4.0.0
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
